### ISSUE TITLE
Planning: SEO and Web marketing notes

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#10]
## Assessment Criteria
- Business model is clear and comprehensive in the final project and README.md file.
- Include Search Engine Optimisation (SEO) and Web Marketing strategies and implementations in final project and documentation in README.md.

## Tasks
- [x] Create business model - sketch and review notes.
- [x] Create thorough list of Web marketing strategies. - review notes.
- [x] Add meta descriptions and keywords in notes for final checklist.
- [x] Add inclusions - robots.txt and sitemap.xml files - review notes.
- [x] Suitable rel tags for external links.
- [x] Plan social media pages - (Facebook - mandatory, Instagram - might include)

### Additional Notes:
Don't forget lighthouse SEO test for testing throughout the build.
