### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#11]
As a **user**, I can **safely register/login/logout on the site** so that **I can access more features on the store**.

### Acceptance Criteria
- Users can register their details and safely login using AllAuth.
- Site admin can securely manage users within the admin panel.

### Tasks
- [x] Install Django AllAuth.
- [x] Add new apps to installed apps in settings.py.
- [x] Add 'site id', 'login redirect url' and 'logout redirect url' constants to settings.py
- [x] Add allAuth to middleware in settings.py
- [x] Add account email verification constant with value of "none" as not using email verification for login. (MAYBE)
- [x] Migrate changes.
- [x] Add 'accounts' URL path to project/urls.py.
- [x] Update base.html to include urls for login/logout/signup pages.
- [x] Add register/login links to navigation section in base.html and run server to check if login pages have been added.
- [x] Copy the allauth template files to the projects templates directory and add content to files for all html pages.
- [x] Deploy and test functionality.

### Additional Notes:
add any notes here
