### ISSUE TITLE
Create bookstore app

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#12]
As a **user**, I can **access the bookstore** so that **I can view items available to purchase**.

### Acceptance Criteria
- Users can access a basic structure of the bookstore page. 
- Users can search for books using the search bar.
- Users can click on a book to read more about it on the detail page.
- Users can filter the categories on a top side bar - refer to wireframe. (MIGHT INCLUDE)

### Tasks
- [x] Create bookstore app, view and url.  **- add message and test functionality before moving on.**
- [x] Create fixtures folder with all book info.
- [x] Add basic page structure to bookstore.html - refer to wireframe.
- [x] Add book media, include no img photo to be included if book has no image file.
- [x] Create search bar and search functionality. **- test functionality before checking this box.**
- [x] Display message to user if their search result was not found.
- [x] Create category filter functionality **- test - decide to include.**
- [x] Create item detail page and view.
- [x] Test deployed version and ensure it matches development version before moving on.

### Additional Notes:
- bug - displaying img logo in header and footer on book detail page.
- issue with deployment at this point so will be testing within the dev version for now.
- search functionality needs work

- won't be including category feature at this point, causing errors with the models.
