### ISSUE TITLE
Create user registration functionality

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#13]
As a **user**, I can **register/login/logout of the site** so that **I can access all the features of the site and save my information**.

### Acceptance Criteria
- Register/Login/Logout pages are available by accessing their links on the navigation bar.
- User can register their new account and login.
- Login message displayed on the top of the page with login status and username. 
- Register/Login buttons are displayed when logged out, logout button displayed when logged in.

### Tasks
- [x] Add to sign up sign in sign out templates within allauth files to extend base template.
- [x] Add to forms on pages and basic styling.
- [x] Add new user to test functionality.

### Additional Notes:
add any notes here
