### ISSUE TITLE
Create basket app

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#14]
As a **user**, I can **add items to my basket** so that **I can purchase many items at a time**.

### Acceptance Criteria
- Users can select items from the bookstore and add them to their basket.
- Users can access the basket page to find all the items they have added. Items can be removed.
- Toast messages will be displayed when items are added or removed from the basket

### Tasks
- [x] Create basket app, view, urls and template. **Test functionality before moving forward**
- [x] Create basket functionality.
- [x] Install toasts and create html files to store info for toast messages.
- [x] Test deployed version.

### Additional Notes:
- having some issues with the initial add to basket functionality. Not sure how to fix the views to correctly add items to basket.
