### ISSUE TITLE
Create checkout app

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#15]
As a **user**, I can **checkout items from my basket** so that **I can purchase items for delivery**.

### Acceptance Criteria
- Users can checkout their basket items.
- Stripe payment and order can be viewed on the stripe website.
- Users can view and order summary after they have completed the payment.

### Tasks
- [x] Create checkout app, view, urls and template. **Test functionality before moving forward**
- [x] Set up Stripe API information within env file.
- [x] Create checkout functionality and test using stripe test information.
- [x] Create order summary info to be displayed when successful order is placed.
- [x] Test deployed version is the same as development version.

### Additional Notes:
add any notes here
