### ISSUE TITLE
Book Detail

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#16]
As a **user**, I can **click on a book title on the bookstore page** so that **I can find more information and features on the book detail page**.

### Acceptance Criteria
- Users can find more info about a book within the book detail page.
- Users can find all information about the book as well as a description of the contents.
- Users can find reviews on the page as well as a form to add a review themselves.

### Tasks
- [x] Create book detail template, view and urls. Test functionality.
- [x] Add item information to template.
- [x] Create Review section to display available reviews/testimonials from other users.
- [x] Create 'add review' form.
- [x] Test deployed version.

### Additional Notes:
Reviews and review form will be similar to comments on blog project- check there for reference.

- bug with submitting review - redirect. 
- deployment not working atm.
