### ISSUE TITLE
404 Page 

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#19]
As a **developer**, I can **create custom error handling** so that **I can create a better user experience and a user is easily redirected to the home page**.

### Acceptance Criteria
- If a 404 error occurs the user will be redirected to the 404 page.
- The user receives an apology message and will be redirected to the home page.

### Tasks
- [x] Create 404 template and urls.
- [x] Add 404 error handling within the view.
- [x] Run server and attach a non existing page to the URL to create an error and test functionality.
- [x] Test deployed version to match the development version.

### Additional Notes:
Refer to PP4 notes for additional resources.
