### ISSUE TITLE
Create user profile

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#20]
As a **registered-user**, I can **access my user profile** so that **I can edit any of my personal details, and view my basket or my wish list/ favourites**.

### Acceptance Criteria
- Logged in users can access their profile page by clicking the icon next to their name in the logged in status.
- Users can access a form to edit their personal details, or their delivery details.
- Users can click a button to their basket page, or their wish-list and favourites.

### Tasks
- [x] Create profile view, template and urls. - Test functionality
- [x] Add features to profile template.
- [x] Deploy and test functionality 

### Additional Notes:
decide on which features will be included still - wish list and favourites
