### ISSUE TITLE
Home page features - Sell your books

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#23]
As a **registered-user**, I can **enquire about selling my old books on the home page** so that **I can help in promoting sustainability and waste management**.

### Acceptance Criteria
- Registered users can submit an enquiry form, giving the details of second hand books they own for a potential purchase from the business.
- Users can submit multiple books on one form by clicking on the option.
- Information on the section is available on the home page to all users, but only registered users can access the form. 
- A link to sign up will be available for unregistered users.
- This is to encourage people to sign up to the site.

### Tasks
- [x] Add section to home page template.
- [x] Create dynamic form to include form fields as well as an option to select multiple books and duplicate the form.
- [x] Test deployed version.

### Additional Notes:
add any notes here
