### ISSUE TITLE
Social Media Links

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#27]
As a **user**, I can **access the business social media accounts** so that **I can follow and share their posts and products with my friends**.

### Acceptance Criteria
- Users can access legit business pages on instagram and facebook links found in the footer.

### Tasks
- [x] Create Facebook business page
- [x] Create Instagram business page (if we have time)
- [x] Add images and posts and add their links to the sections in the footer.
- [x] Don't forget target=_blank !
- [x] run server and test functionality
- [x] test deployed version

### Additional Notes:
Will add Instagram if there's enough time within this iteration. I think it would be nice to utilise two working link icons for social media.
- Might include instagram photos for instagram links in a home page section above footer - refer to sketches.
