### ISSUE TITLE
Refactoring - Design 

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#28]
As a **developer**, I can **ensure that the front-end of my site is elegant, appealing and efficient** so that **I can guarantee a good user experience across all platforms**.

### Acceptance Criteria
- All pages should be refactored where needed, so the design of the site is accessible and intriguing.
- Deployed and development versions should be identical.

### Tasks
- [x] Check all pages for any design issues and make changes to areas that don't look right.
- [x] Ensure all colours of font and backgrounds meet accessibility guidelines.
- [x] Ensure all images used are the correct size and the resolution is perfect.
- [x] Ensure all banners with images and font are good enough contrast to meet all accessibility guidelines.
- [x] Test that deployed version front-end pages are the same as in development. - fix any errors.

### Additional Notes:
Refer to wireframes and sketch notes for guidance.
Refer to all accessibility guidelines available online.
