### ISSUE TITLE
Refactoring - Responsive design 

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#29]
As a **developer**, I can **enable good responsive design standards across my site** so that **users can access the site and its features across all platforms and screen sizes.**.

### Acceptance Criteria
- All pages design should be good and easy to see on mobile, tablet and computer screen sizes.
- Site should be compatible with all browsers.
- Media queries should be well labeled and easy to find within the CSS file.

### Tasks
- [x] Test mobile and tablet screen sizes using dev tools and make any changes needed to the CSS.
- [x] Test development and deployed version to ensure all is working properly.
- [x] Test site on phone and iPad, ensure all pages look okay.
- [x] Make note of any wont-fix sections.

### Additional Notes:
book detail page has a slight push - not sure what is causing it.
