### ISSUE TITLE
Refactoring 

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#30]
As a **developer**, I can **refactor python and JS functions** so that **I can ensure good performance on my site and maintain industry standards for 'clean code'**.

### Tasks
- [x] Ensure functions are a good standard.
- [x] refer to assessment criteria for any more details
- [x] remove all commented out code.
- [x] ensure all docstrings are correct and detailed.
- [x] ensure all login_required decorators are present where they are meant to be.
- [x] CSS file tidy up
- [x] image file names are consistent - all unused images deleted.
- [x] add sitemap and robots files

### Additional Notes:
add any notes here
