### ISSUE TITLE
Testing - Validation

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#31]
As a **developer**, I can **validate my code using validator programs** so that **ensure my code is clear or any errors.**.

### Acceptance Criteria
- All pages should pass through their appropriate validator service with no major issues.
- Any errors/ issues that can't be fixed must be noted and added to the appropriate section of README.md documentation.

### Tasks
- [x] Copy all Python files into the validator - remove any issues listed.
- [x] Copy all JavaScript files into the validator - remove any issues listed.
- [x] Copy all HTML files into the validator - fix any errors found. 
- [x] Copy all CSS files into the validator 
- [x] Use the source code of all these files to ensure the DTL tags are ok to be passed through the validator.

### Additional Notes:
add any notes here
