### ISSUE TITLE
Testing - Lighthouse

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#32]
As a **developer**, I can **access google lighthouse testing** so that **I can ensure I have good performance, accessibility and SEO on my site**.

### Acceptance Criteria
- All views should receive green scores for all sections.

### Tasks
- [x] Test all sections in the deployed version
- [x] If scores are low then refer to lighthouse guidelines to improve scores.
- [x] Document final scores in README.md testing sections.

### Additional Notes:
add any notes here
