### ISSUE TITLE
Testing - Automated Testing

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#34]
As a **developer**, I can **create automated testing functions** so that **I can thoroughly test my code**.

### Acceptance Criteria
- Automated testing files can be found in project app files and within TESTING.md file.
- Running unit tests command in the console will run all tests and give results.

### Tasks
- [x] Create testing functions within all app files.
- [x] Fix any functions that aren't passing
- [x] Include screenshots within TESTING.md file.

### Additional Notes:
- only had time to complete basket and bookstore apps
