### ISSUE TITLE
FINAL CHECKLIST - check this off before submission

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#37]
### Tasks
- [x] at least 3 original custom models with associated functionalities, markedly different from those present in the Boutique Ado walkthrough project if they have been used as a basis for your project.

- [x] at least one form on the front end, which provides either admin or regular users with CRUD functionality without having to access the admin panel.

- [x] at least one UI element on the front end, which allows either admin or regular users to delete records in the database without having to access the admin panel.

- [x] evidence of agile methodologies followed during the development of your project in the GitHub repository.

- [x] a robots.txt file.

- [x] a sitemap.xml file.

- [x] descriptive meta tags in the HTML.

- [x] at least one link to an external resource, which makes use of a rel attribute.

- [x] a custom 404 error page.

- [x] evidence of either a real Facebook business page, or mockup of one, for the purposes of digital marketing.

- [x] evidence of a newsletter signup form for the purposes of digital marketing.

- [x] a description of the e-commerce business model including marketing strategies in the README file.

- [x] DEBUG mode set to False.

- [x] working functionality for users to register and log in and out of the application without issues.

- [x] working E-commerce functionality for users to make purchases within the application.

- [x] detailed testing write ups, beyond results of validation tools.

- [x] GitHub project board set to public visibility.

- [x] NO CHANGES TO WORKSPACE WHEN SUBMIT - PUSH EVERYTHING

### Additional Notes:
Keep adding to this throughout the project if needed.
DON'T FORGET TO PUSH EVERYTHING BEFORE SUBMISSION
