### ISSUE TITLE
Planning - bookstore

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#39]
### Tasks
- [x] Create list of all books and their details - title, author, rating, description etc. Refer to models.
- [x] Decide how many products to include.
- [x] Add folder of all book cover images in their correct size. 
- [x] transfer image folder to media project folder.
- [x] Add all data to fixtures.

### Additional Notes:
can add data to fixtures when bookstore app is created
