### ISSUE TITLE
Add stock to model

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#42]
As a **site-admin**, I can **manage stock of each item** so that **users cannot try to purchase items that are out of stock, and maintain a good user experience.**.

### Acceptance Criteria
- Stock number and in stock variable are accessible to admin user.
- Stock can be easily managed for the admin user on the admin panel, and on the book detail page.

### Tasks
- [x] Add stock variables to model and make migrations.
- [x] Register models in admin.py.
- [x] Include in templates.
- [x] Include out of stock message on book detail if books are out of stock **Test**
- [x] include buttons in admin section of book detail.

### Additional Notes:
add any notes here
