### ISSUE TITLE
Initial Deployment

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#7]
As a **developer**, I can **deploy my site to Heroku** so that **I can ensure the development version matches the deployed version**.

### Acceptance Criteria
- Site should deploy on Heroku without any errors.
- Test message should display on the home page url.
- All secret info should be hidden in the config variables.

### Tasks
- [x] Create new project app on Heroku and link to Github repo.
- [x] Include any sensitive information within config variable within the app settings.
- [x] Set up automatic deployments.
- [x] Ensure gunicorn is installed and correct information is stored within the Procfile in the project's root directory.
- [x] add '.heroku.com' to ALLOWED_HOSTS variable in settings.py.
- [x] Manually deploy and test functionality.

### Additional Notes:
Collect static command is causing an error. Not sure where this is coming from! Need to research further.
FIXED: config settings needed help
