### ISSUE TITLE
Create base.html and index.html templates.

### ISSUE THREAD

**Issue by FernVR** [FernVR/the_book_loop#9]
As a **developer**, I can **create views using django templates** so that **I can create a dynamic page that extends functionality across all pages.**

### Acceptance Criteria
- Home page should have a basic view in place.
- Header and Footer information are set up within the base template and able to view on the home page.
- Django file structure is maintained.

### Tasks
- [x] Create base and index html files and include DTL tags to link the pages.
- [x] Create basic structure for header and footer.
- [x] Include correct meta information for the base template.
- [x] Create base.css file and link within the head of base.html - add some styles and test functionality.
- [x] Create basic structure for the home page, refer to the wireframe.
